#The collection of aphorisms from which the bot sends /quote and other scheduled aphorisms
aphorisms = [
            '__He who fights with monsters might take care lest he thereby becomes a monster. And if you gaze for long into an abyss, the abyss gazes also into you.__ ~Nietzsche' , 
            '__What does not kill me, makes me stronger__ ~Nietzsche' , 
            '__What is done out of love always takes place beyond good and evil.__ ~Nietzsche' , 
            '__Man does not strive for happiness; only the Englishman does that.__ ~Nietzsche' , 
            '__There are no facts, only interpretations.__ ~Nietzsche' , 
            '__There are two great European narcotics, alcohol and Christianity.__ ~Nietzsche' , 
            '__Become who you are!.__ ~Nietzsche' , 
            '__The true man wants two things: danger and play.__ ~Nietzsche' , 
            '__My formula for greatness in a human being is amor fati: that one wants nothing to be different, not forward, not backward, not in all eternity.__ ~Nietzsche' , 
            '__The lonely one offers his hand too quickly to whomever he encounters.__ ~Nietzsche', 
            '__There is more wisdom in your body than in your deepest philosophy.__ ~Nietzsche ' , 
            '__A living thing seeks above all to discharge its strength - life itself is will to power.__ ~Nietzsche' , 
            '__My formula for happiness: a Yes, a No, a straight line, a goal.__ ~Nietzsche',
            '__It is not death  that a man should fear but he should fear never beginning to live.__ ~Marcus Aurelius.',
            "__Keep this thought handy when you feel a bit of rage coming on it is not manly to be enraged. Rather, gentleness and civility are more human, and therefore manlier. A real man does not give way to anger and discontent, and such a person has strength, courage, and endurance unlike the angry and complaining. The nearer a man comes to a calm mind, the closer he is to strength.__ ~Marcus Aurelius",
            "__Death smiles at us all; all we can do is smile back at it. __ ~ Marcus Aurelius",
            '__Think of yourself as dead. You have lived your life. Now take what is left and live it properly.__ ~ Marcus Aurelius',
            '__Wherever there is a human, there is an opportunity for kindness.__ ~Seneca',
            '__Self love is more cunning than the most cunning man in the world.__ ~Rochefoucald',
            '__Passion often renders the most clever man a fool, and even sometimes renders the most foolish man clever.__ ~Rochefoucald',
            '__Self-love is the greatest of flatterers.__ ~Rochefoucald',
            '__The moderation of those who are happy arises from the calm which good fortune bestows upon their temper.__ ~Rochefoucald',
            '__We have all sufficient strength to support the misfortunes of others.__ ~Rochefoucald',
            '__Philosophy triumphs easily over past evils and future evils; but present evils triumph over it.__ ~Rochefoucald'
            '__If we had no faults we should not take so much pleasure in noting those of others.__ ~Rochefoucald',
            '__To establish ourselves in the world we do everything to appear as if we were established.__ ~Rochefoucald',
            '__The happiness or unhappiness of men depends no less upon their dispositions than their fortunes.__ ~Rochefoucald',
            '__If there is a pure love, exempt from the mixture of our other passions, it is that which is concealed at the bottom of the heart and of which even our- selves are ignorant.__ ~Rochefoucald',
            '__It is more disgraceful to distrust than to be deceived by our friends.__ ~Rochefoucald',
            '__Those who know their minds do not necessarily know their hearts.__ ~Rochefoucald',
            '__One kind of flirtation is to boast we never flirt.__ ~Rochefoucald',
            '__A man would rather say evil of himself than say nothing.__ ~Rochefoucald',
            '__We often boast that we are never bored, but yet we are so conceited that we do not perceive how often we bore others.__ ~Rochefouclad',
            '__The refusal of praise is only the wish to be praised twice.__ ~Rochefoucald',
            '__There are some persons who only disgust with their abilities, there are persons who please even with their faults__ ~Rochefoucald',
            '__People who comprehend a thing to its very depths rarely stay faithful to it forever. For they have brought its depths into the light of day: and in the depths there is always much that is unpleasant to see.__ ~Nietzsche',
            '__The cure for love is still in most cases that ancient radical medicine: love in return.__ ~Nietzsche',
            '__Fortune cures us of many faults that reason could not.__ ~Rochefoucald',
            '__However rare true love is, true friendship is rarer.__~Rochefoucald',
            '__Timidity is a fault which is dangerous to blame in those we desire to cure of it__~Rochefoucald',
            '__We often go from love to ambition, but we never return from ambition to love.__~Rochefoucald',
            '__Sobriety is the love of health, or an in- capacity to eat much. ~Rochefoucald',
            '__We never forget things so well as when we are tired of talking of them__ ~Rochefoucald',
            '__We are very fond of reading others characters, but we do not like to be read ourselves__~Rochefoucald',
            '__The greatest skill of the least skilful is to know how to submit to the direction of another__~Rochefoucald',
            '__Why we cry out so much against maxims which lay bare the heart of man, is because we fear that our own heart shall be laid bare.__ ~Rochefoucald',
            '__The labor of the body frees us from the pains of the mind, and thus makes the poor happy__~Rochefoucald',
            '__Few things are needed to make a wise man happy; nothing can make a fool content; that is why most men are miserable.__~Rochefoucald',
            '__We trouble ourselves less to become happy, than to make others believe we are so__~Rochefoucald',
            '__Wisdom is to the soul what health is to the body.__ ~Rochefoucald',
            '__Before strongly desiring anything we should examine what happiness he has who possesses it.__ ~Rochefoucald',
            '__We commonly praise the good hearts of those who admire us. __~Rochefoucald',
            '__A man to whom no one is pleasing is much more unhappy than one who pleases nobody.__~Rochefoucald',
            '__A well regulated mind sees all things as they should be seen, appraises them at their proper value, turns them to its own advantage, and adheres firmly to its own opinions as it knows all their force and weight.__~Rochefoucald',
            '__There is a kind of love, the excess of which forbids jealous__~Rochefoucald',
            '__Infidelities should extinguish love, and we ought not to be jealous when we have cause to be so. No person can escape causing jealousy who are worthy of exciting it.__~Rochefoucald',
            "__Flirtation is at the bottom of woman's nature, although all do not practise it, some being restrained by fear, others by sense__~Rochefoucald",
            '__There are different kinds of curiosity: one springs from interest, which makes us desire to know everything that may be profitable to us; another from pride, which springs from a desire of knowing what others are ignorant of.__~Rochefoucald',
            '__As rivers are lost in the sea so are virtues in self__~Rochefoucald',
            '__Idleness and fear keeps us in the path of duty, but our virtue often gets the praise.__~Rochefoucald',
            '__However deceitful hope may be, yet she carries us on pleasantly to the end of life__~Rochefoucald',
            '__Pride will not owe, self-love will not pay.__~Rochefoucald',
            '__True love is like ghosts, which everybody talks about and few have seen.__~Rochefoucald',
            '__Envy is destroyed by true friendship, flirtation by true love__~Rochefoucald',
            '__We always fear to see those whom we love when we have been flirting with others.__~Rochefoucald',
            '__That which makes us believe so easily that others have defects is that we all so easily believe what we wish.__~Rochefoucald',
            '__There are those who avoid our jealousy, of whom we ought to be jealous. __~Rochefoucald',
            '__There is nothing more natural, nor more deceptive, than to believe that we are beloved.__~Rochefoucald',
            '__"All truth is simple" - Is that not a compound lie ?__~Nietzsche',
            '__The mason employed on the building of a house may be quite ignorant of its general design; or at any rate, he may not keep it constantly in mind. So it is with man: in working through the days and hours of his life, he takes little thought of its character as a whole.__~Schopenhauer ',
            '__An angry man opens his mouth and shuts his eyes.__~Cato, The Elder',
            '__A thinker sees his own actions as experiments and questions as attempts to find out something. Success and failure are for him answers above all. To be annoyed or feel remorse because something goes wrong that he leaves to those who act because they have received orders and who have to reckon with a beating when his lordship is not satisfied with the result.__~Nietzsche',
            '__I assess the power of a will by how much resistance, pain, torture it endures and knows how to turn to its advantage.__~Nietzsche',
            '__One must learn to love.-- This is what happens to us in music: First one has to learn to hear a figure and melody at all, to detect and distinguish it, to isolate it and delimit it as a separate life. Then it requires some exertion and good will to tolerate it in spite of its strangeness, to be patient with its appearance and expression, and kindhearted about its oddity. Finally there comes a moment when we are used to it, when we wait for it, when we sense that we should miss it if it were missing; and now it continues to compel and enchant us relentlessly until we have become its humble and enraptured lovers who desire nothing better from the world than it and only it.__~Nietzsche',
            '__There are fine things which are more brilliant when unfinished than when finished too much.__~Rochefoucald',
            '__More persons exist without self-love than without envy__~Rochefoucald',
            '__What makes us see that men know their faults better than we imagine, is that they are never wrong when they speak of their conduct; the same self-love that usually blinds them enlightens them, and gives them such views as to make them suppress or disguise the smallest thing that might be censured.__~Rochefoucald',
            '__The first impulse of joy which we feel at the happiness of our friends arises neither from our natural goodness nor from friendship; it is the result of self-love, which flatters us with being lucky in our own turn, or in reaping something from the good fortune of our friends.__~Rochefoucald',
            '__In the adversity of our best friends we always find something which is not wholly displeasing to us.__~Rochefoucald',
            '__Self-love takes care to prevent him whom we flatter from being him who most flatters us.__~Rochefoucald',
            '__Everyone seeks to find his pleasure and his advantage at the expense of others. We prefer ourselves always to those with whom we intend to live, and they almost always perceive the preference. It is this which disturbs and destroys society. We should discover a means to hide this love of selection since it is too ingrained in us to be in our power to destroy. We should make our pleasure that of other persons, to humour, never to wound their self-love.__~Rochefoucald',
            '__What makes this falseness so universal, is that as our qualities are uncertain and confused, so too, are our tastes; we do not see things exactly as they are, we value them more or less than they are worth, and do not bring them into unison with ourselves in a manner which suits them or suits our condition or qualities. This mistake gives rise to an infinite number of falsities in the taste and in the mind. Our self-love is flattered by all that presents itself to us under the guise of good.__~Rochefoucald',
            '__It would seem that even self-love may be the dupe of goodness and forget itself when we work for others. And yet it is but taking the shortest way to arrive at its aim, taking usury under the pretext of giving, in fact winning everybody in a subtle and de- licate manner.__~Rochefoucald',
            '__ There is no passion wherein self-love reigns so powerfully as in love, and one is always more ready to sacrifice the peace of the loved one than his own.__~Rochefoucald',
            '__We only appreciate our good or evil in pro- portion to our self-love.__~Rochefoucald',
            '__The wit of most women rather strengthens their folly than their reason.__~Rochefoucald',
            '__For every minute you remain angry, you give up sixty seconds of peace of mind.__~Emerson',
            '__Nothing is at last sacred but the integrity of your own mind__~Emerson',
            '__The glory of friendship is not the outstretched hand, not the kindly smile, nor the joy of companionship; it is the spiritual inspiration that comes to one when you discover that someone else believes in you and is willing to trust you with a friendship.__~Emerson',
            '__If we encounter a man of rare intellect, we should ask him what books he reads.__~Emerson',
            '__Consider all the experiences you have had in life. Whether years ago or merely earlier today. Notice how insubstantial - how dreamlike - what remains is. All of these experiences have left very little residue. Many of these experiences took great effort to secure. Notice how your view of future experiences does not seem to take this evanescence to account. It is almost like you expect these future experiences will really make you happy in some lasting way. Where did you get that idea?__ ~Sam Harris, Moments',
            "__Marry, and you will regret it; do not marry, you will also regret it; marry or do not marry, you will regret it either way. Laugh at the world's foolishness, you will regret it; weep over it, you will regret that too; laugh at the world's foolishness or weep over it, you will regret both. Believe a woman, you will regret it; believe her not, you will also regret it. Hang yourself, you will regret it; do not hang yourself, and you will regret that too; hang yourself or don't hang yourself, you'll regret it either way; whether you hang yourself or do not hang yourself, you will regret both. This, gentlemen, is the essence of all philosophy.__ Soren Kierkegaard",
            '__Life is not a problem to be solved, but a reality to be experienced.__~Kierkegaard',
            '__To live alone one must be a beast or a god, says Aristotle. Leaving out the third case: one must be both, a philosopher.__~Nietzsche',
            "__One of love's greatest drawbacks is that, for a while at least, it is in danger of making us seriously happy.__~deBotton",
            '__Our greatest pleasure consists in being admired; but the admirers, even if there is every cause, are not very keen to express their admiration. And so the happiest man is he who has managed sincerely to admire himself, no matter how.__~Schopenhauer',
            '__We must learn to suffer whatever we cannot avoid. Our life is composed, like the harmony of the world, of discords as well as of different tones, sweet and harsh, sharp and flat, soft and loud. If a musician liked only some of them, what could he sing? He has got to know how to use all of them and blend them together. So too must we with good and ill, which are of one substance with our life.__~Montaigne',
            '__Despite our proud claim to dominate nature, we are still its victims because we have not yet learned to dominate ourselves.__ ~Carl Jung',
            '__Anyone who imagines that all fruits ripen at the same time as the strawberries knows nothing about grapes.__ ~Paracelsus ',
            '__Hope in reality is the worst of all evils because it prolongs the torments of man__~Nietzsche',
            '__Before getting married, ask yourself: will I be able to maintain a good conversation with this person until old age? Everything else is transient in a marriage.__ ~Nietzsche',
            '__In love there is always something mad and in madness there is always something right.__ ~Nietzsche',
            '__Nobody is so crazy that he cannot find another crazy person who understands him.__ ~Nietzsche',
            '__The will to overcome a passion is, in short, only the will of another passion or of many other passions.__ ~Nietzsche',
            '__Sensuality often overtakes the growth of love, so that the root remains weak and easy to pluck out.__ ~Nietzsche',
            '__Everything that irritates us about others can lead us to an understanding of ourselves.__ ~ C. G. Jung',
            '__Carry out each act as if it were the last of your life, freed from all randomness and passionate deviation from the rule of reason and from pretense and self-love and dissatisfaction with what has been allotted to you.__ ~Marcus Aurelius',
            '__The world would give you few gifts, believe me. So if you want a life, steal it.__ ~Lou Andreas-Salome',
            '__If only it were all so simple! If only there were evil people somewhere insidiously committing evil deeds, and it were necessary only to separate them from the rest of us and destroy them. But the line dividing good and evil cuts through the heart of every human being. And who is willing to destroy a piece of his own heart?__~Alexander Solzhenitsyn',
            '__Everybody finds that to abuse in another which he finds worthy of abuse in himself.__ ~Rochefoucald'
            '__One kind of happiness is to know exactly at what point to be miserable.__ ~Rochefoucald',
            '__When we do not find peace of mind in ourselves it is useless to seek it elsewhere.__ ~Rochefoucald',
            '__When we are tired of loving we are quite content if our mistress should become faithless, to loose us from our fidelity.__ ~Rochefoucald',
            '__Sobriety is the love of health, or an incapacity to eat much__ ~Rochefoucald',
            '__Civility often hides half its understanding, and when it meets with an opinionated man who defends the bad side, spares him the disgrace of giving way__ ~Rochefoucald',
            '__If there is much art in speaking to the purpose, there is no less in knowing when to be silent.__ ~Rochefoucald',
            "__Let us be grateful to the people who make us happy; they are the charming gardeners who make our souls blossom.__ ~Marcel Proust",
            "__We still draw the conclusions of judgments we consider false, of teachings in which we no longer believe - our feelings make us do it.__   ~Nietzsche",
            "__The learned judge correctly that people of all ages have believed they know what is good and evil, praise and blameworthy. But it is a prejudice of the learned that we now know better than any other age.__  ~Nietzsche",
            "__First stage: man sees in every feeling of indisposition and misfortune something for which he has to make someone else suffer- in doing so he becomes conscious of the power he still possesses and this consoles him. Second stage: man sees in every feeling of indisposition and misfortune a punishment, that is to say, an atonement for guilt and the means of gettingfree from the evil spell of a real or supposed injustice. When he realises this advantage which misfortune brings with it, he no longer believes he has to make someone else suffer for it - he renounces this kind of satisfaction because he now has another.__     ~Nietzsche",
            "__To be a teacher in the right sense is to be a learner. Instruction begins when you, the teacher, learn from the learner, put yourself in his place so that you may understand what he understands and the way he understands it.__   ~Kierkegaard",
            "__One could construe the life of man as a great discourse in which the various people represent different parts of speech (the same might apply to states). How many people are just adjectives, interjections, conjunctions, adverbs? How few are substantives, active verbs, how many are copulas? Human relations are like the irregular verbs in a number of languages where nearly all verbs are irregular.__    ~Kierkegaard",
            "__Above all do not forget your duty to love yourself; do not permit the fact that you have been set apart from life in a way, been prevented from participating actively in it, and that you are superflous in the obtruse eyes of a busy world, above all, do not permit this to deprive you of your idea of yourself, as if your life, if lived in inwardness, did not have just as much meaning and worth as that of any human being in the eyes of all-wise Governance, and considerably more than the busy, busiest haste of busy-ness - busy with wasting life and losing itself.__     ~Kierkegaard",
            "__It belongs to the imperfection of everything human that man can only attain his desire by passing through its opposite.__    ~Kierkegaard",
            "__I may live for thirty years, or perhaps forty, or maybe just one day: therefore I have resolved to use this day, or whatever I have to say in these thirty years or whatever I have to say this one day I may have to live I have resolved to use it in such a way that if not one day in my whole past life has been used well, this one by the help of God will be__   ~Kierkegaard",
            "__Deep within every human being there still lives the anxiety over the possibility of being alone in the world, forgotten by God, overlooked among the millions and millions in this enormous household. One keeps this anxiety at a distance by looking at the many round about who are related to him as kin and friends, but the anxiety is still there, nevertheless, and one hardly dares think of how he would feel if all this were taken away.__     ~Kierkegaard",
            "__Death cannot explain itself. The earnestness consists precisely in this, that the observer must explain it to himself.__   ~Kierkegaard",
            "__It is perfectly true, as the philosophers say, that life must be understood backwards. But they forget the other proposition, that it must be lived forwards.__   ~Kierkegaard",
            "__The tyrant dies and his rule is over; the martyr dies and his rule begins__   ~Kierkegaard",
            "__Someone in despair despairs over something. So, for a moment, it seems, but only for a moment. That same instant the true despair shows itself, or despair in its true guise. In despairing over something he was really despairing over himself, and he wants now to be rid of himself.__    ~Kierkegaard",
            "__Out of love, God becomes man. He says: 'See, here is what it is to be a human being.'__   ~Kierkegaard" ,
            "__A man should not strive to eliminate his complexes but to get in accord with them: they are legitimately what directs his conduct in the world.__   ~Freud",
            "__Love and work....work and love, that's all there is.__   ~Freud",
            "__Men are more moral than they think and far mote immoral than they can imagine.__    ~Freud",
            "__Just as no one can be forced into belief, so no one can be forced into unbelief.__   ~Freud",
            "__Most people don't really want freedom, because freedom involves responsibility, and most people are frightened of responsibility.__   ~Freud",
            "__Neurosis is the inability to tolerate ambiguity.__    ~Freud",
            "__Neurotics complain of their illness, but they make the most of it, and when it comes to talking it away from them they will defend it likes a lioness her young.__    ~Freud",
            "__Religion is an illusion and it derives it's strength from the fact that it falls in with our instinctual desires__    ~Freud",
            "__The ego is not master in its own house__.     ~Freud",
            "__Time spent with cats is never wasted.__     ~Freud",
            "__We are never so defenseless against suffering as when we love__.    ~Freud",
            "__Whoever loves becomes humble. Those who love have, so to speak, pawned a part of their narcissism__.    ~Freud",
            "__He that has eyes to see and ears to hear may convince himself that no mortal can keep a secret. If his lips are silent, he chatters with his fingertips; betrayal oozes out of him at every pore.__    ~Freud",
            "__It would be very nice if there was a God who created the world and was a benevolent providence and if there were a moral order in the universe and an after-life; but it is a very striking fact that all this is exactly as we are bound to wish it to be.__    ~Freud",
            "__One is very crazy when in love__   ~Freud",
            "__The great question that has never been answered, and which I have not yet been able to answer despite my thirty years of research into the feminine soul, is 'What does a woman want?'__    ~Freud",
            "__Further, it is easy to observe that the libidinal object-cathexis does not raise self-regard. The effect of dependence upon the loved object is to lower that feeling: a person in love is humble. A person who loves has, so to speak, forfeited a part of his narcissism, and it can only be replaced by his being loved.__   **S. Freud in On Narcissism (1914), Papers on Metapsychology**",
            "__This ideal ego is now the target of the self-love which was enjoyed in the childhood by the actual ego. The subjects narcissism makes its appearance displaced on to this new ideal ego, which, like the infantile ego, finds itself possessed of every perfection that is of value. As always where the libido is concerned, man has here again shown himself incapable of giving up a satisfaction he had once enjoyed. He is not willing to forgo the narcissistic perfection of his childhood; and when, as he grows up, he is disturbed by the admonitions of others and by the awakening of his own critical judgement, so that he can no longer retain that perfection, he seeks to recover it in the new form of an ego ideal . What he projects before him as his ideal is the substitute for the lost narcissism of his childhood in which he was his own ideal.__     **S. Freud in On Narcissism (1914), Papers on Metapsychology**",
            "__The process of repression is not to be regarded as an event which takes place once, the results of which are permanent, as when some living thing has been killed ad from that time onward is dead; repression demands a persistent expenditure of force, and if this were to cease the success of the repression would be jeopardized, so that a fresh act of repression would be necessary. We may suppose that the repressed exercises a continuous pressure in the direction of the conscious, so that this pressure must be balanced by an uneasing counter-pressure. Thus the maintenance of a repression involves an uninterrupted expenditure of force, while its removal results in a saving from an economic point of view.__      **S. Freud in On Narcissism (1914), Papers on Metapsychology**",
            "__Anxiety, then, is in the first place something that is felt. We call it an affective state, although we are also ignorant of what an affect is. As a feeling, anxiety has a very marked character of unpleasure. But that is not the whole of its quality. Not every unpleasure can be called anxiety, for there are other feelings, such as tension, pain or mourning, which have the character of unpleasure. Thus anxiety must have other distinctive features besides this unpleasure. Can we succeed in understanding the differences between these various un-pleasurable affects?__       **S. Freud in Inhibitions, Symptoms and Anxiety**",
            "__The problem of how anxiety arises in connection with repression may be no simple one; but we may legitimately hold firmly to the idea that ego is the actual seat of anxiety and give up our earlier view that the cathectic energy of the repressed impulse is automatically turned into anxiety.__    **S. Freud in Inhibitions, Symptoms and Anxiety**",
            "__What is a symptom that one 'brings' to analysis? It is always a subjective solution to some contradiction or impase. And it is a solution that usually makes one's life very complicated; it comes with some degree of suffering. Yet it is a solution, and it involves serious subjective investment. The work of analysis consists in forcing out the contradiction 'solved' by the system, in relating the symptom to the singular contradiction of which it is a solution. Psychoanalysis does not solve the contradiction; rather, it solves its solution (given by the symptom). It 'bores a hole' where the symptom has built a dense net of significations. And the subject needs to 'reconstruct' herself as a part of this contradiction, as directly implied in it.__     **Alenka Zupancic, What is Sex?**",

            "__And this opens the space for a different hypothesis; it is as if sexual meaning, so generously produced by the unconscious, were here to mask the reality of a more fundamental negativity at work in sexuality, to separate us from it by a screen that derives its efficacy from the fact that it is itself a means of satisfaction -- satisfaction through meaning, satisfaction in the production of sexual meaning, and (as the observe of this) in the production of meaning of the sexual. Paradoxical as this might sound, one of the primary tasks of psychoanalysis is to slowly but thoroughly deactivate the path of this satisfaction, to render it useless. To produce sex as absoluetely and intrinsincally meaningless, not as the ultimate horizon of all humanly produced meaning. That is to say : to restore sex in its dimension of the Real.__          **Alenka Zupancic, What is Sex?**",
            "__That this very special transference, that we have the right, which is placed there at the culmen of what is involved in love, do we not see there being dismissed, though with contrary accents, two words of love, that of Alcibiades and that of Socrates which, as I said, with accents which are not the same, fall under the same defintion: love is to give what one does not have to someone who does not want it.__          **Seminar XII, Crucial Problems for Psychoanalysis, Jacques Lacan**",
            "__Anxiety is thus an intermediary term between jouissance and desire in so far as desire is constituted and founded upon the anxiety phase, once anxiety has been got through.__          **Seminar X, Anxiety, Jacques Lacan**",
            
            "__The meeting of two personalities is like the contact of two chemical substances: if there is any reaction, both are transformed.__          **Modern Man in Search of  Soul, Carl Jung.**",
            "__A psychotherapist learns little or noting from his successes__       **Modern Man in Search of  Soul, Carl Jung.**",
            "__Sensation establishes what is actually given, thinking enables us to recognize its meaning, feeling tells us its value, and finally intuition points to the possibilities of the whence and whither that lie within the immediate facts.__              **Modern Man in Search of  Soul, Carl Jung.**",
            "__Dreams may give expression to ineluctable truths, to philosophical pronouncements, illusions, wild fantasies, memories, plans, anticipations, irrational experiences, even telepathic visions, and heaven knows what besides. One thing we ought never to forget: almost the half of our lives is passed in a more or less unconscious state.__              **Modern Man in Search of Soul, Carl Jung**",
            "__We must never forget in dream analysis, even for a moment, that we move on treacherous ground where nothing is certain but uncertainty. A suitable warning to the dream interpreter--if only it were not so paradoxical-- would be: 'Do anything you like but don't try to understand!'__                 **Modern Man in Search of Soul, Carl Jung**",
            "__What we call fantasy is simply spontaneous psychic activity; and it wells up whenever the repressive action of the conscious mind relaxes or ceases altogether, as in sleep.__           **Modern Man in Search of Soul, Carl Jung**",
            "__There appears to be a conscience in mankind which severely punishes the man who does not somehow and at some time, at whatever cost to his pride, ceases to defend and assert himself, and instead confess himself fallible and human.__                       **Modern Man in Search of Soul, Carl Jung**",
            "__Painful though as it may be, this is in itself a gain--for what is inferior or even worthless belongs to me as my shadow and gives me substance and mass. How can i be substantial if I fail to cast a shadow? I must have a dark side also if I am able to be whole; and inasmuch as I become conscious of mmy shadow I also remember that I am a human being like any other__             **Modern Man in Search of Soul, Carl Jung**",
            "__Of we try to give our attention to uninteresting matters, we soon notice how feeble our powers of concentration are. We ourselves, like them, are dependent upon emotional undercurrents.__                 **Modern Man in Search of Soul, Carl Jung**",
            "__Chance occurrences are repellent to a mind that loves order.__                  **Modern Man in Search of Soul, Carl Jung.**",
            "__What happens regularly is easily observed because we are prepared for it. Knowledge and skill are only needed in situations where the course of events is arbitrarily disrupted in a way hard to fathom.__                **Modern Man in Search of soul, Carl Jung**",
            "__Psychology teaches us that, in a certain sense, there is nothing in the psyche that is old; nothing that can really, definitively die away.__              **Modern Man in Search of Soul, Carl Jung**",
            "__Whatever is given to us by the past is adapted to the possibilities and demands of the future.__                  **Modern Man in Search of Soul, Carl Jung**",

            "__The meaning and design of a problem seem not to lie in its solution, but in our working at it incessantly.__               **Modern Man in Search of Soul, Carl Jung**",
            "__Do we ever understand what we think? We only understand that thinking which is a mere equation, and from which nothing comes out but what we have put in.__                                              **Modern Man in Search of Soul, Carl Jung**",
            "__True expression consists in giving form to what is observed.__                  **Modern Man in Search of Soul, Carl Jung**",
            "__There is no misunderstanding in nature' they are only to be found in the realms that man calls 'understanding'.__               **Modern Man in Search of Soul, Carl Jung**",
            "__On the contrary, every civilized human being, whatever his conscious development, is still an archaic man at the deeper levels of his psyche.__                           **Modern Man in Search of Soul, Carl Jung**",
            "__Whenever we are dealing with an unconscious content, we are dealing with something that is constitutively unconscious, that is to say that it only registers in reality in the form of repression, as repression (and not something that first is, and is then repressed). This is why if we simply focus on the content, we lose this specificity (we lose this dimension of not-fully-being as the very mode of being of this particular thing, which is precisely the mode of repression). Repression is not something that we can simply lift and get access in this way to the 'unstained' unconscious content/representation. If we reduce the Freudian notion of the unconscious to the difference between a content that is present tp the conscious and a content that is 'repressed from it', if we reduce it to the opposition between being or not being conscious of something (or between consciously accepting or not accepting something), we lose it entirely.__                **Alenka Zupancic, Hegel and Freud: Between Aufhebung and Verneinung**",
            "__Reason isn't the removal of desire, reason is instead the actualization of desire.__                 **Todd McGown, On Hegel's Phenomenolgy of Spirit**",
            "__To say that something is identical with itself means that it is distinct from all its particular properties, that it cannot be reduced to them. “A rose is a rose” means that a rose is something more than all its features: there is some je ne sais quoi which makes it a rose, something “more in a rose than the rose itself.” As this last example indicates, we are also dealing here with what Lacan called objet petit a, the mysterious X beneath all its properties that makes an object what it is, that sustains its unique identity. More precisely, this “more” oscillates between the sublime and the ridiculous or vulgar, if not obscene: to say “a law is a law” means that, even if it is unjust and arbitrary, an instrument of corruption even, a law remains a law and has to be respected. The minimal structure of identity (which is always a self-identity since it is, as Hegel knew it, a category of reflection) is thus 1-1-a: a thing is itself in contrast with its determinate properties, and objet a is the unfathomable excess that sustains this identity.__                                       **Slavoj Zizek, Can One Be a Hegelian Today?**",
            "__We exist because the sun sees us.__                      **Carl Jung, Collected Works Vol.5, par.283***",
            "__Freud in his realization that one (a psychoanalyst) does not cure someone through the communication of knowledge to him or her (the patient). Elsewhere, he wrote: If the doctor transfers his knowledge to the patient as a piece of information, it has no result. [Or] it has that of setting the analysis in motion, of which the first signs are often expressions of denial. The patient knows after this what he did not before--the sense of his symptom; yet he knows it just as little as he did before. Thus we learn that there is more than one kind of ignorance...Knowledge must rest on an internal change in the patient.--                 **Bruce Fink, A Clinical Introduction of Freud**",

            "__It is no small matter to acknowledge one's yearning. For this may need to make a particular effort at honest. All too many do not want to know where their yearning is, because it would seem to them impossible or too distressing. And yet yearning is the way of life.__                  **Carl Jung, The Red Book, p.249**",
            "__Why, indeed, would the unconscious be more worthy of being recognized than the defenses that oppose it in the subject, so successfully that the defenses seem no less real than it? I am not reviving here the shoddy Nietzschean notion of the lie o life, nor am I marveling at the fact that one believes one believes, nor do I accept that to will something one need but want it badly enough. But I am asking where the peace that ensues in recognizing an unconscious tendency comes from if the latter is not truer than what restrained it in the conflict. For some time now this peace has, moreover, been quickly proving illusory, for psychoanalysts, not content to recognize as unconscious the defenses to be attributed to the ego, have increasingly identified the defense mechanisms--displacement of the object, turning back against the subject, regression of the form--with the very dynamic that Freud analyzed in the tendency, which thus seems to persist in the defenses with no more than a change of sign. Haven't people gone too far when they submit that the drive itself may be made conscious by the defense so that the subject won't recognize himself in it?__                               **Jacques Lacan, 'The Freudian Thing' in Ecritis**",
            "A truth, if it must be said, is not easy to recognize once it has become received. Not that there aren't any established truths, but they are so easily confused with the reality that surrounds them with the sign of spirit, in order to pay them homage, to regard them as having come from another world. It is not the whole story to attribute to a sort of blindness on man's part the fact that truth is never to him a finer looking girl than when the light, held aloft by his arm as in the proverbial emblem, unexpectedly illuminates her nakedness. And one must play the fool a bit to feign knowing nothing of what happens next. But stupidity remains characterized by bullheaded frankness when one wonders where one could have been looking for her before, the emblem scarcely helping to indicate the well, an unseemly and even malodorous place, rather than the jewelry box in which every precious form must be preserved intact.__                    **Jacques Lacan, 'The Freudian Thing' in Ecritis**",
            "__Naturally the infant's own mother is more likely to be good enough than some other person, since this active adaptation demands an easy and unresented preoccupation with the one infant; in fact, success infant-care depends on the fact of devotion, not on the cleverness or intellectual enlightenment.__                               **Donald Winnicott, Transitional Objects and Transitional Phenomena (1953)**",
            
            "__All through the period of latency children learn to feel for other people who help them in their helplessness and satisfy their needs, a love which is on the model of, and a continuation of, their relation as sucklings to their nursing mother....A child's intercourse with anyone responsible for care affords him an unending source of sexual excitation and satisfaction from his erotogenic zones.__               **S. Freud, in Three Essays on Sexuailty, p.222-223**",

            "__In psychoanalysis as we know it there is no trauma that is outside the individual's omnipotence. Everything eventually comes under ego-control, and thus becomes related to secondary processes.__                       **Donald Winnicott, The Theory of the Parent-Infant Relationship (1960)**",

            "__The paradox is that what is good and bad in the infant's environment is not in fact a projection, but in spite of this it is necessary, if the individual infant is to develop healthily, that everything shall seem to him to be a projection. Here we find omnipotence and the pleasure principle (Freud) in operation, as they certainly are in earliest infancy; and to this observation we can add that the recognition of a true 'not-me' is a matter of the intellect; it belongs to extreme sophistication and to the maturity of the individual.__                  **Donald Winnicott, The Theory of Parent-Infant Relationship (1960)**",

            "__It should be noted that mothers who have it in them to provide good-enough care can be enabled to do better by being cared for themselves n a way that acknowledges the essential nature of their task. Mothers who do not have it in them to provide good-enough care cannot be made good enough by mere instruction.__                                         **Donald Winnicott, The Theory of Parent-Infant Relationship (1960)**",

            "__Holding includes especially the physical holding of the infant, which is a form of loving. It is perhaps the only way in which a mother can show the infant her love. There are those who can hold an infant and those who cannot; the latter quickly produce in the infant a sense of insecurity, and distressed crying. All this leads right up to, includes, and co-exists with the establishment of the infant's first object relationships and his first experiences of instinctual gratification.__                                    **Donald Winnicott, The Theory of Parent-Infant Relationship (1960)**",

            "__The analytic process reflects the interplay of three subjectivities: that of the analyst, of the analysand, and of the analytic third. The analytic third is a creation of the analyst and analysand, and at the same time the analyst and analysand (qua analyst and analysand) are created by the analytic third (there is no analyst, no analysand, and no analysis in the absence of the third).__                       **Thomas Ogden, The Analytic Third**",

            "__Language is such a marvelous and fruitful secret--because when someone speaks merely for the sake of speaking, he utters the most splendid, most original truths. But if he wants to speak about something definite, capricious language makes him say the most ridiculous an confused stuff. This is also the cause of the hatred that so many serious people feel towards language. They notice its mischief, but not the fact that the chattering they scorn is the infinitely serious aspect of language.__                          **Novalis, Philosophical Writings**",

            "__On the whole, Lacan's theory reverses our intuitive assumption about the relation between the word and the thing. The thing is not waiting for a word to represent it; rather it is the word that creates the thing. Language always precedes the world it represents. La can calls upon the insights of structural linguistics in order to demonstrate that the words have a function that transcends the need to communicate.....Thus, when Lacan says that the unconscious is 'structured like a language' (Seminar III, p.167), this means that the unconscious is not the repository of the drives or the storage room for 'thing-representations'(Freud, SE IV, pp.295-6). The unconscious does not have a fixed content.__                    **The Cambridge Companion to Lacan, in 'The Birth of the Unconscious' section**",
            "__As soon as the subject is supposed to know exits somewhere...there is transference.__                **Jacques Lacan, Seminar XI: Four Fundamentals of Psychoanalysis, p.232",

##Lichtenberg Aphorisms

"__The great trick of regarding small deviations from the truth as the truth itself—a trick upon which the whole of differential calculus is based—isalso the basis of our ingenious thoughts, where the whole thing would often collapse if we were to consider the deviations with philosophical rigor.__                         **G.C Lichtenberg, Philosophical Writings and Waste Books**",

"__It is a question whether in the arts and sciences a best is possible beyond which our understanding cannot reach. This point is perhaps infinitely distant, yet with every approximation we have less ahead of us.__                         **G.C Lichtenberg, Philosophical Writings and Waste Books**",

"__The discovery of the most significant truths depends upon a subtle abstraction, yet our everyday life, with its competencies, habits, and routines, constantly endeavors to make us incapable of this. It is the work of philosophers to unlearn these trivial mindless abilities, which we have acquired through observation since childhood. Thus even as a child, a philosopher should already be educated differently.__                     **G.C Lichtenberg, Philosophical Writings and Waste Books**",

"__When we look at an object, we simultaneously see many others but less distinctly. The question is whether this is habituation or whether it has another cause. If the first is the case, we should be able to become accustomed to seeing things distinctly without directly attending to them.  __                  **G.C Lichtenberg, Philosophical Writings and Waste Books**",

"__In some sciences, the endeavor to discover a universal principle may often be just as fruitless as the endeavor of a mineralogist to discover some primary universal element through the compounding of which all minerals arose. Nature creates neither genera nor species, but individua, and in our shortsightedness, we must seek out similarities to be able to retain many things simultaneously. These concepts become more and more inaccurate the broader the categories are which we create.__                     **G.C Lichtenberg, Philosophical Writings and Waste Books**",

"__The greatest things in the world are brought about by others, to which we pay no attention, insignificant causes that we overlook but that eventually accumulate.__                  **G.C Lichtenberg, Philosophical Writings and Waste Books**",

"__In his novel Émile, Rousseau rightly calls accent the soul of speech. We often think people stupid, but upon examination we discover it is only their simple tone or accent that makes them seem this way. Since tone is not conveyed in writing, the reader must be directed to it by being shown more clearly through phrasing where it belongs. This is what distinguishes ordinary speech from a letter and what should distinguish a merely printed speech from one that is actually delivered.__                   **G.C Lichtenberg, Philosophical Writings and Waste Books**",

"__The influence of style upon our attitudes and thoughts, which I have discussed elsewhere, is evident even in Linnaeus, who is usually quite precise; he suggests that stones grow, plants grow and live, and animals grow, live, and sense. The first is false because the growth of a stone bears no resemblance to that of plants and animals. The intensification of expression, which he noticed in the latter series, probably led him to include the former in this classification.4__                     **G.C Lichtenberg, Philosophical Writings and Waste Books**",

"__To match versification to the thought is a very difficult art, the neglect of which is responsible for much ridiculous verse. Versification and thought are related to one another as in everyday life savoir-vivre is to occupation. __                     **G.C Lichtenberg, Philosophical Writings and Waste Books**",

"__If we wish to create a philosophy of use to us in life or wish to give general principles for a perpetually contented life, we must certainly abstract from what introduces too much diversity in our observations—much as in mechanics we ignore friction or other similar particular properties of bodies, so our calculations are not so cumbersome, or we at least replace them with a single letter. Insignificant mishaps undeniably introduce much uncertainty into our practical principles, so we must dismiss them and attend to overcoming the significant ones. This is undoubtedly the true meaning of certain propositions in the Stoic philosophy.5__                     **G.C Lichtenberg, Philosophical Writings and Waste Books**",

"__The superstition of ordinary people originates in their early and all too zealous instruction in religion, where they hear of secrets, miracles, and acts of the devil and believe it probable such things might occur everywhere in anything. If, however, they were first taught about nature, they would more readily regard the supernatural and mysterious aspects of religion with greater awe rather than considering them quite commonplace as they now do—so commonplace, indeed, that they do not think it extraordinary when someone tells them that today six angels crossed the street. Neither are the images in the Bible good for children.__                    **G.C Lichtenberg, Philosophical Writings and Waste Books**",

"__Habit might be called a moral friction: something that does not allow the mind to glide easily over things but joins it to them so it cannot easily free itself.__                   **G.C Lichtenberg, Philosophical Writings and Waste Books**",

"__In the everyday question of how to do something in the best possible way, we are seeking a certain maximum.__                    **G.C Lichtenberg, Philosophical Writings and Waste Books**",

"__The proof advanced by philosophers that there is a future life, which consists in their saying that were it not the case then God could not reward our final moments, belongs to the proofs by analogy. We reward only after the fact, thus God must also. We do this out of lack of anticipation, but where we are not thus hindered we also reward in advance, as we pay in advance our university tuition. Might God not also have paid in advance?  When Plutarch says that the victor is not crowned during the battle but only afterward, he is similarly obscure; it is a mere analogy, a kind of proof that is both false and cruel.__                   **G.C Lichtenberg, Philosophical Writings and Waste Books**",

"__Death is a constant quantity—only pain is variable and may be intensified infinitely. Those who defend torture must admit this, or they torture in vain. In many, pain reaches a maximum and yet is < death.__                   **G.C Lichtenberg, Philosophical Writings and Waste Books**",

"__The argument against the materialists offered in Herr Unzer’s journal Der Arzt, and that derives from the mutability of our body, truly has some force.  Certainly the parts of my body are no longer me when I am a few years older, so how could successive souls, so to speak, impart consciousness to one another? One might respond that the transformation is very gradual, just as traditions have been passed on even though every eighty years the earth itself is different. This is how La Mettrie would respond. Another__                   **G.C Lichtenberg, Philosophical Writings and Waste Books**",

"__continues to act, perhaps in a manner like a spark to gun powder.__                  **G.C Lichtenberg, Philosophical Writings and Waste Books**",

"__Prejudices are, so to speak, the acquired instincts of human beings: through prejudice we can accomplish many things we would find too difficult to think through to the point of decision.__                    **G.C Lichtenberg, Philosophical Writings and Waste Books**",

"__According to Home, in seeing and hearing we do not sense the immediate contact of bodies outside of us in the same way as with other senses. (If we had no eyes, perhaps the feeling of sensations would seem as equally to occur within us; it is only because we have eyes that we locate sensations where we see a cause for them p.m.)__                     **G.C Lichtenberg, Philosophical Writings and Waste Books**",

"__Whenever we read a good thought, we should see if something similar might be thought and said about another matter, assuming here that it has some affinity with the former. This is a kind of analysis of thought that perhapssome scholars adopt without saying.  Understanding the meaning of a word in our mother tongue often takes us many years. I also have in mind understanding the meaning tone can lend to a word. The meaning of a word is, if I may express myself mathematically, given by a formula in which the tone is the variable and the word is the constant quantity. This opens the possibility of infinitely enriching language without increasing the number of words. I have found that the phrase “It is good” is pronounced in five different ways, each time with another meaning, which is often determined by yet a third variable, namely, the facial expression.__                     **G.C Lichtenberg, Philosophical Writings and Waste Books**",

"__If substances possess properties that allow others to apprehend them, then we can at once be members of different worlds without being conscious of ourselves in more than one of them, for the properties of substances are, in a manner of speaking, permeable. Thus we can die in one world and continue to live in another.__                    **G.C Lichtenberg, Philosophical Writings and Waste Books**",

"__If we could organize our most abstract principles, which our reason apprehends without much previous sensation, in such a way as to facilitate a transition to their application, it would produce a practical metaphysics— only this transition currently eludes our metaphysics.  __                   **G.C Lichtenberg, Philosophical Writings and Waste Books**",

"__We ourselves are the measure of the miraculous. Were we to seek a common measure, the miraculous would disappear and all things be reduced to the same size.__                   **G.C Lichtenberg, Philosophical Writings and Waste Books**",

"__Minds or spirits without an external world must be strange indeed; since the ground of every thought lies within it, even the most fantastic combinations of ideas would always be correct. We call people insane when the order of their concepts no longer corresponds to the sequence of events in our orderly world; thus a careful observation of nature, or even mathematics, is certainly the most effective preventative of insanity; nature is, so to speak, the guide rope by which our thoughts are lead, so they do not stray. __                    **G.C Lichtenberg, Philosophical Writings and Waste Books**",

"__The grocer who weighs something is as much engaged in placing an unknown quantity on one side and a known quantity on the other as the algebraist.__                     **G.C Lichtenberg, Philosophical Writings and Waste Books**",

"__The conflict over meaning and being, which has done so much harm in religion, might have done more good had it been fought on other fields, for it is a common source of our misfortune that we believe things actually__                    **G.C Lichtenberg, Philosophical Writings and Waste Books**",

"__to be what they really only mean.  It is an entirely unavoidable defect of all languages that they express only the genera of concepts and seldom can say adequately what they wish to say.  For if we compare our words with things, we discover that the latter consist in a wholly different order from the former. The properties we observe in our souls are connected in such a way that it is not easy to delineate a boundary between them, but the words with which we express them are not constituted in this way. Two successive and related properties are expressed with signs that seem to indicate no relationship with one another. We should be able to decline words philosophically and to indicate their relationship through modifications. In the geometrical analysis of a line a, one indefinite section of it is called x; the other section is not called y, as in ordinary life, but a – x. This is why mathematical language has such great advantages over ordinary language.__                    **G.C Lichtenberg, Philosophical Writings and Waste Books**",

"__When Plato says passions and natural desires are the wings of the soul, his expression is enlightening; such comparisons illuminate the matter and are, as it were, translations of the difficult concepts of one man into a language__                  **G.C Lichtenberg, Philosophical Writings and Waste Books**",

"__understood by all—true definitions.  Undoubtedly creatures might exist whose organs are so sensitive that they are unable to reach through a ray of light, just as we are unable to reach__                  **G.C Lichtenberg, Philosophical Writings and Waste Books**",

"__through a stone because our hands would be destroyed.  Perhaps a thought is the cause of all motion in the world, and the philosophers who taught that the world is an animal perhaps arrived at the idea this way; but they may not have expressed themselves as exactly as they perhaps should have. Our entire world is only the effect upon matter of one of God’s thoughts.__                   **G.C Lichtenberg, Philosophical Writings and Waste Books**",

"__The world is a body common to all people; changes in it bring about changes in the souls of all people who are facing only a part. Not to exist means to natural scientists, at least a certain class of them, the same as not to be perceived.__                    **G.C Lichtenberg, Philosophical Writings and Waste Books**",

"__It never occurs to the peasant who believes the moon is no bigger than a plough wheel that at a distance of a few miles an entire church appears no larger than a white speck, while the moon always appears the same size.  Since he possesses these ideas separately, what prevents him from connecting them? In his everyday life, he does connect ideas, perhaps in more elaborate ways than these. This reflection should grab the attention of philosophers, for in certain connections of thought they are perhaps still peasants. We think early enough in life, but we do not know that we are thinking any more than we know we are growing or digesting; among ordinary people, few ever realize this. A close observation of things outside us leads quickly back to the point of observation, that is, ourselves; conversely, anyone who once becomes fully aware of himself is readily led to the observation of the world around him. Be attentive, experience nothing in vain, measure and compare—this is the entire law of philosophy.__                   **G.C Lichtenberg, Philosophical Writings and Waste Books**",

"__Whatever one sees, does, or reads, it should always be brought to such a degree of clarity that one can at least answer the most general objections against it and then it can become part of the structure of our science. To this structure nothing disputable should be added. If something generally assumed cannot be united with our system, then perhaps we are still missing foundational ideas, and discovering this is a great achievement. __                     **G.C Lichtenberg, Philosophical Writings and Waste Books**",

"__Human philosophy is never other than the philosophy of one particular individual corrected by that of others, even fools, according to the rules of a rational appraisal of degrees of probability. Propositions to which everyone assents are true. If they are not true, then there is no truth.  Other propositions we are often compelled to hold true on the assurance of experts, and any man would believe such propositions were he to find himself in the same circumstances. Where this is not the case, we have a particular philosophy and not one established in the council of mankind.  Superstition itself is a local philosophy voicing its opinion as well. __                     **G.C Lichtenberg, Philosophical Writings and Waste Books**",

"__Growing wiser means becoming increasingly acquainted with the errors to which our instrument of feeling and judging may be subject. Today, cautiousness in judgment is to be recommended to each and every one. If we reap but one incontestable truth every ten years from each philosopher, our harvest would be rich enough.  __                  **G.C Lichtenberg, Philosophical Writings and Waste Books**",

"__Every mathematical expression is in effect a mirror.__                   **G.C Lichtenberg, Philosophical Writings and Waste Books**",

"__Many relations in nature are neither arithmetical nor geometrical and are thus difficult for us to specify or describe. Perhaps such relations can be reduced to those we have already discovered.__                     **G.C Lichtenberg, Philosophical Writings and Waste Books**",

"__Rain, snow, and wind follow one another in such a way that we discern no certain law in their order. But we conceive of laws only in order to simplify our conceptions of things, just as we create races.__                     **G.C Lichtenberg, Philosophical Writings and Waste Books**",

"__Late one evening, Socrates wanted into his house but was scolded from the window by Xanthippe, who finally dumped the chamber pot on his head.  “With such a storm,” he remarked, “I knew it would rain.”__                  **G.C Lichtenberg, Philosophical Writings and Waste Books**",

"__What would this be had I discovered it myself according to the structure of my own system of thought?__                  **G.C Lichtenberg, Philosophical Writings and Waste Books**",

"__Make natural observations before subtle ones, and seek always a simple and natural explanation.__                    **G.C Lichtenberg, Philosophical Writings and Waste Books**",

"__Things most often forgotten, places overlooked, and things accepted without question deserve most often to be investigated.__                    **G.C Lichtenberg, Philosophical Writings and Waste Books**",

"__Silence is not silence, and white is not white—we only suppose this. What we do not observe does not exist for us.__                     **G.C Lichtenberg, Philosophical Writings and Waste Books**",

"__Perhaps this arose in me only through constant habituation since childhood.  What insights we would have if we could once divest our wealth of truths of things not essentially true but only accrued through frequent repetition.__                     **G.C Lichtenberg, Philosophical Writings and Waste Books**",

"__The most common ideas and those upon which everyone agrees deserve most often to be investigated, but in misgivings about this one should always remember what Franklin says in his Experiments and Observations on Electricity: “If we propose our objections modestly we shall tho’ mistaken, deserve a censure less severe, than when we are both mistaken and insolent.”__                   **G.C Lichtenberg, Philosophical Writings and Waste Books**",

"__Ask yourself whether you can explain the insignificant details; this is the only means to create an accurate system, probe its strengths, and put your readings to use.__                    **G.C Lichtenberg, Philosophical Writings and Waste Books**",

"__A single word might be replaced with six; we express too much with one and the same word.__                  **G.C Lichtenberg, Philosophical Writings and Waste Books**",

"__To investigate what is mutable and what eternal in a matter, and at least to indicate where certainty ceases.__                  **G.C Lichtenberg, Philosophical Writings and Waste Books**",

"__We know for certain how to designate the limits of error, and where doubt remains, precise inaccuracy begins.__                  **G.C Lichtenberg, Philosophical Writings and Waste Books**"
]
