#The collection of aphorisms from which the bot sends /quote and other scheduled aphorisms
aphorisms = [
            '__He who fights with monsters might take care lest he thereby becomes a monster. And if you gaze for long into an abyss, the abyss gazes also into you.__ ~Nietzsche' , 
            '__What does not kill me, makes me stronger__ ~Nietzsche' , 
            '__What is done out of love always takes place beyond good and evil.__ ~Nietzsche' , 
            '__Man does not strive for happiness; only the Englishman does that.__ ~Nietzsche' , 
            '__There are no facts, only interpretations.__ ~Nietzsche' , 
            '__There are two great European narcotics, alcohol and Christianity.__ ~Nietzsche' , 
            '__Become who you are!.__ ~Nietzsche' , 
            '__The true man wants two things: danger and play.__ ~Nietzsche' , 
            '__My formula for greatness in a human being is amor fati: that one wants nothing to be different, not forward, not backward, not in all eternity.__ ~Nietzsche' , 
            '__The lonely one offers his hand too quickly to whomever he encounters.__ ~Nietzsche', 
            '__There is more wisdom in your body than in your deepest philosophy.__ ~Nietzsche ' , 
            '__A living thing seeks above all to discharge its strength - life itself is will to power.__ ~Nietzsche' , 
            '__My formula for happiness: a Yes, a No, a straight line, a goal.__ ~Nietzsche',
            '__It is not death  that a man should fear but he should fear never beginning to live.__ ~Marcus Aurelius.',
            "__Keep this thought handy when you feel a bit of rage coming on it is not manly to be enraged. Rather, gentleness and civility are more human, and therefore manlier. A real man does not give way to anger and discontent, and such a person has strength, courage, and endurance unlike the angry and complaining. The nearer a man comes to a calm mind, the closer he is to strength.__ ~Marcus Aurelius",
            "__Death smiles at us all; all we can do is smile back at it. __ ~ Marcus Aurelius",
            '__Think of yourself as dead. You have lived your life. Now take what is left and live it properly.__ ~ Marcus Aurelius',
            '__Wherever there is a human, there is an opportunity for kindness.__ ~Seneca',
            '__Self love is more cunning than the most cunning man in the world.__ ~Rochefoucald',
            '__Passion often renders the most clever man a fool, and even sometimes renders the most foolish man clever.__ ~Rochefoucald',
            '__Self-love is the greatest of flatterers.__ ~Rochefoucald',
            '__The moderation of those who are happy arises from the calm which good fortune bestows upon their temper.__ ~Rochefoucald',
            '__We have all sufficient strength to support the misfortunes of others.__ ~Rochefoucald',
            '__Philosophy triumphs easily over past evils and future evils; but present evils triumph over it.__ ~Rochefoucald'
            '__If we had no faults we should not take so much pleasure in noting those of others.__ ~Rochefoucald',
            '__To establish ourselves in the world we do everything to appear as if we were established.__ ~Rochefoucald',
            '__The happiness or unhappiness of men depends no less upon their dispositions than their fortunes.__ ~Rochefoucald',
            '__If there is a pure love, exempt from the mixture of our other passions, it is that which is concealed at the bottom of the heart and of which even our- selves are ignorant.__ ~Rochefoucald',
            '__It is more disgraceful to distrust than to be deceived by our friends.__ ~Rochefoucald',
            '__Those who know their minds do not necessarily know their hearts.__ ~Rochefoucald',
            '__One kind of flirtation is to boast we never flirt.__ ~Rochefoucald',
            '__A man would rather say evil of himself than say nothing.__ ~Rochefoucald',
            '__We often boast that we are never bored, but yet we are so conceited that we do not perceive how often we bore others.__ ~Rochefouclad',
            '__The refusal of praise is only the wish to be praised twice.__ ~Rochefoucald',
            '__There are some persons who only disgust with their abilities, there are persons who please even with their faults__ ~Rochefoucald',
            '__People who comprehend a thing to its very depths rarely stay faithful to it forever. For they have brought its depths into the light of day: and in the depths there is always much that is unpleasant to see.__ ~Nietzsche',
            '__The cure for love is still in most cases that ancient radical medicine: love in return.__ ~Nietzsche',
            '__Fortune cures us of many faults that reason could not.__ ~Rochefoucald',
            '__However rare true love is, true friendship is rarer.__~Rochefoucald',
            '__Timidity is a fault which is dangerous to blame in those we desire to cure of it__~Rochefoucald',
            '__We often go from love to ambition, but we never return from ambition to love.__~Rochefoucald',
            '__Sobriety is the love of health, or an in- capacity to eat much. ~Rochefoucald',
            '__We never forget things so well as when we are tired of talking of them__ ~Rochefoucald',
            '__We are very fond of reading others characters, but we do not like to be read ourselves__~Rochefoucald',
            '__The greatest skill of the least skilful is to know how to submit to the direction of another__~Rochefoucald',
            '__Why we cry out so much against maxims which lay bare the heart of man, is because we fear that our own heart shall be laid bare.__ ~Rochefoucald',
            '__The labor of the body frees us from the pains of the mind, and thus makes the poor happy__~Rochefoucald',
            '__Few things are needed to make a wise man happy; nothing can make a fool content; that is why most men are miserable.__~Rochefoucald',
            '__We trouble ourselves less to become happy, than to make others believe we are so__~Rochefoucald',
            '__Wisdom is to the soul what health is to the body.__ ~Rochefoucald',
            '__Before strongly desiring anything we should examine what happiness he has who possesses it.__ ~Rochefoucald',
            '__We commonly praise the good hearts of those who admire us. __~Rochefoucald',
            '__A man to whom no one is pleasing is much more unhappy than one who pleases nobody.__~Rochefoucald',
            '__A well regulated mind sees all things as they should be seen, appraises them at their proper value, turns them to its own advantage, and adheres firmly to its own opinions as it knows all their force and weight.__~Rochefoucald',
            '__There is a kind of love, the excess of which forbids jealous__~Rochefoucald',
            '__Infidelities should extinguish love, and we ought not to be jealous when we have cause to be so. No person can escape causing jealousy who are worthy of exciting it.__~Rochefoucald',
            "__Flirtation is at the bottom of woman's nature, although all do not practise it, some being restrained by fear, others by sense__~Rochefoucald",
            '__There are different kinds of curiosity: one springs from interest, which makes us desire to know everything that may be profitable to us; another from pride, which springs from a desire of knowing what others are ignorant of.__~Rochefoucald',
            '__As rivers are lost in the sea so are virtues in self__~Rochefoucald',
            '__Idleness and fear keeps us in the path of duty, but our virtue often gets the praise.__~Rochefoucald',
            '__However deceitful hope may be, yet she carries us on pleasantly to the end of life__~Rochefoucald',
            '__Pride will not owe, self-love will not pay.__~Rochefoucald',
            '__True love is like ghosts, which everybody talks about and few have seen.__~Rochefoucald',
            '__Envy is destroyed by true friendship, flirtation by true love__~Rochefoucald',
            '__We always fear to see those whom we love when we have been flirting with others.__~Rochefoucald',
            '__That which makes us believe so easily that others have defects is that we all so easily believe what we wish.__~Rochefoucald',
            '__There are those who avoid our jealousy, of whom we ought to be jealous. __~Rochefoucald',
            '__There is nothing more natural, nor more deceptive, than to believe that we are beloved.__~Rochefoucald',
            '__"All truth is simple" - Is that not a compound lie ?__~Nietzsche',
            '__The mason employed on the building of a house may be quite ignorant of its general design; or at any rate, he may not keep it constantly in mind. So it is with man: in working through the days and hours of his life, he takes little thought of its character as a whole.__~Schopenhauer ',
            '__An angry man opens his mouth and shuts his eyes.__~Cato, The Elder',
            '__A thinker sees his own actions as experiments and questions as attempts to find out something. Success and failure are for him answers above all. To be annoyed or feel remorse because something goes wrong that he leaves to those who act because they have received orders and who have to reckon with a beating when his lordship is not satisfied with the result.__~Nietzsche',
            '__I assess the power of a will by how much resistance, pain, torture it endures and knows how to turn to its advantage.__~Nietzsche',
            '__One must learn to love.-- This is what happens to us in music: First one has to learn to hear a figure and melody at all, to detect and distinguish it, to isolate it and delimit it as a separate life. Then it requires some exertion and good will to tolerate it in spite of its strangeness, to be patient with its appearance and expression, and kindhearted about its oddity. Finally there comes a moment when we are used to it, when we wait for it, when we sense that we should miss it if it were missing; and now it continues to compel and enchant us relentlessly until we have become its humble and enraptured lovers who desire nothing better from the world than it and only it.__~Nietzsche',
            '__There are fine things which are more brilliant when unfinished than when finished too much.__~Rochefoucald',
            '__More persons exist without self-love than without envy__~Rochefoucald',
            '__What makes us see that men know their faults better than we imagine, is that they are never wrong when they speak of their conduct; the same self-love that usually blinds them enlightens them, and gives them such views as to make them suppress or disguise the smallest thing that might be censured.__~Rochefoucald',
            '__The first impulse of joy which we feel at the happiness of our friends arises neither from our natural goodness nor from friendship; it is the result of self-love, which flatters us with being lucky in our own turn, or in reaping something from the good fortune of our friends.__~Rochefoucald',
            '__In the adversity of our best friends we always find something which is not wholly displeasing to us.__~Rochefoucald',
            '__Self-love takes care to prevent him whom we flatter from being him who most flatters us.__~Rochefoucald',
            '__Everyone seeks to find his pleasure and his advantage at the expense of others. We prefer ourselves always to those with whom we intend to live, and they almost always perceive the preference. It is this which disturbs and destroys society. We should discover a means to hide this love of selection since it is too ingrained in us to be in our power to destroy. We should make our pleasure that of other persons, to humour, never to wound their self-love.__~Rochefoucald',
            '__What makes this falseness so universal, is that as our qualities are uncertain and confused, so too, are our tastes; we do not see things exactly as they are, we value them more or less than they are worth, and do not bring them into unison with ourselves in a manner which suits them or suits our condition or qualities. This mistake gives rise to an infinite number of falsities in the taste and in the mind. Our self-love is flattered by all that presents itself to us under the guise of good.__~Rochefoucald',
            '__It would seem that even self-love may be the dupe of goodness and forget itself when we work for others. And yet it is but taking the shortest way to arrive at its aim, taking usury under the pretext of giving, in fact winning everybody in a subtle and de- licate manner.__~Rochefoucald',
            '__ There is no passion wherein self-love reigns so powerfully as in love, and one is always more ready to sacrifice the peace of the loved one than his own.__~Rochefoucald',
            '__We only appreciate our good or evil in pro- portion to our self-love.__~Rochefoucald',
            '__The wit of most women rather strengthens their folly than their reason.__~Rochefoucald',
            '__For every minute you remain angry, you give up sixty seconds of peace of mind.__~Emerson',
            '__Nothing is at last sacred but the integrity of your own mind__~Emerson',
            '__The glory of friendship is not the outstretched hand, not the kindly smile, nor the joy of companionship; it is the spiritual inspiration that comes to one when you discover that someone else believes in you and is willing to trust you with a friendship.__~Emerson',
            '__If we encounter a man of rare intellect, we should ask him what books he reads.__~Emerson',
            '__Consider all the experiences you have had in life. Whether years ago or merely earlier today. Notice how insubstantial - how dreamlike - what remains is. All of these experiences have left very little residue. Many of these experiences took great effort to secure. Notice how your view of future experiences does not seem to take this evanescence to account. It is almost like you expect these future experiences will really make you happy in some lasting way. Where did you get that idea?__ ~Sam Harris, Moments',
            "__Marry, and you will regret it; do not marry, you will also regret it; marry or do not marry, you will regret it either way. Laugh at the world's foolishness, you will regret it; weep over it, you will regret that too; laugh at the world's foolishness or weep over it, you will regret both. Believe a woman, you will regret it; believe her not, you will also regret it. Hang yourself, you will regret it; do not hang yourself, and you will regret that too; hang yourself or don't hang yourself, you'll regret it either way; whether you hang yourself or do not hang yourself, you will regret both. This, gentlemen, is the essence of all philosophy.__ Soren Kierkegaard",
            '__Life is not a problem to be solved, but a reality to be experienced.__~Kierkegaard',
            '__To live alone one must be a beast or a god, says Aristotle. Leaving out the third case: one must be both, a philosopher.__~Nietzsche',
            "__One of love's greatest drawbacks is that, for a while at least, it is in danger of making us seriously happy.__~deBotton",
            '__Our greatest pleasure consists in being admired; but the admirers, even if there is every cause, are not very keen to express their admiration. And so the happiest man is he who has managed sincerely to admire himself, no matter how.__~Schopenhauer',
            '__We must learn to suffer whatever we cannot avoid. Our life is composed, like the harmony of the world, of discords as well as of different tones, sweet and harsh, sharp and flat, soft and loud. If a musician liked only some of them, what could he sing? He has got to know how to use all of them and blend them together. So too must we with good and ill, which are of one substance with our life.__~Montaigne',
            '__Despite our proud claim to dominate nature, we are still its victims because we have not yet learned to dominate ourselves.__ ~Carl Jung',
            '__Anyone who imagines that all fruits ripen at the same time as the strawberries knows nothing about grapes.__ ~Paracelsus ',
            '__Hope in reality is the worst of all evils because it prolongs the torments of man__~Nietzsche',
            '__Before getting married, ask yourself: will I be able to maintain a good conversation with this person until old age? Everything else is transient in a marriage.__ ~Nietzsche',
            '__In love there is always something mad and in madness there is always something right.__ ~Nietzsche',
            '__Nobody is so crazy that he cannot find another crazy person who understands him.__ ~Nietzsche',
            '__The will to overcome a passion is, in short, only the will of another passion or of many other passions.__ ~Nietzsche',
            '__Sensuality often overtakes the growth of love, so that the root remains weak and easy to pluck out.__ ~Nietzsche',
            '__Everything that irritates us about others can lead us to an understanding of ourselves.__ ~ C. G. Jung',
            '__Carry out each act as if it were the last of your life, freed from all randomness and passionate deviation from the rule of reason and from pretense and self-love and dissatisfaction with what has been allotted to you.__ ~Marcus Aurelius',
            '__The world would give you few gifts, believe me. So if you want a life, steal it.__ ~Lou Andreas-Salome',
            '__If only it were all so simple! If only there were evil people somewhere insidiously committing evil deeds, and it were necessary only to separate them from the rest of us and destroy them. But the line dividing good and evil cuts through the heart of every human being. And who is willing to destroy a piece of his own heart?__~Alexander Solzhenitsyn',
            '__Everybody finds that to abuse in another which he finds worthy of abuse in himself.__ ~Rochefoucald'
            '__One kind of happiness is to know exactly at what point to be miserable.__ ~Rochefoucald',
            '__When we do not find peace of mind in ourselves it is useless to seek it elsewhere.__ ~Rochefoucald',
            '__When we are tired of loving we are quite content if our mistress should become faithless, to loose us from our fidelity.__ ~Rochefoucald',
            '__Sobriety is the love of health, or an incapacity to eat much__ ~Rochefoucald',
            '__Civility often hides half its understanding, and when it meets with an opinionated man who defends the bad side, spares him the disgrace of giving way__ ~Rochefoucald',
            '__If there is much art in speaking to the purpose, there is no less in knowing when to be silent.__ ~Rochefoucald',
            "__Let us be grateful to the people who make us happy; they are the charming gardeners who make our souls blossom.__ ~Marcel Proust",
            "__We still draw the conclusions of judgments we consider false, of teachings in which we no longer believe - our feelings make us do it.__   ~Nietzsche",
            "__The learned judge correctly that people of all ages have believed they know what is good and evil, praise and blameworthy. But it is a prejudice of the learned that we now know better than any other age.__  ~Nietzsche",
            "__First stage: man sees in every feeling of indisposition and misfortune something for which he has to make someone else suffer- in doing so he becomes conscious of the power he still possesses and this consoles him. Second stage: man sees in every feeling of indisposition and misfortune a punishment, that is to say, an atonement for guilt and the means of gettingfree from the evil spell of a real or supposed injustice. When he realises this advantage which misfortune brings with it, he no longer believes he has to make someone else suffer for it - he renounces this kind of satisfaction because he now has another.__     ~Nietzsche",
            "__To be a teacher in the right sense is to be a learner. Instruction begins when you, the teacher, learn from the learner, put yourself in his place so that you may understand what he understands and the way he understands it.__   ~Kierkegaard",
            "__One could construe the life of man as a great discourse in which the various people represent different parts of speech (the same might apply to states). How many people are just adjectives, interjections, conjunctions, adverbs? How few are substantives, active verbs, how many are copulas? Human relations are like the irregular verbs in a number of languages where nearly all verbs are irregular.__    ~Kierkegaard",
            "__Above all do not forget your duty to love yourself; do not permit the fact that you have been set apart from life in a way, been prevented from participating actively in it, and that you are superflous in the obtruse eyes of a busy world, above all, do not permit this to deprive you of your idea of yourself, as if your life, if lived in inwardness, did not have just as much meaning and worth as that of any human being in the eyes of all-wise Governance, and considerably more than the busy, busiest haste of busy-ness - busy with wasting life and losing itself.__     ~Kierkegaard",
            "__It belongs to the imperfection of everything human that man can only attain his desire by passing through its opposite.__    ~Kierkegaard",
            "__I may live for thirty years, or perhaps forty, or maybe just one day: therefore I have resolved to use this day, or whatever I have to say in these thirty years or whatever I have to say this one day I may have to live I have resolved to use it in such a way that if not one day in my whole past life has been used well, this one by the help of God will be__   ~Kierkegaard",
            "__Deep within every human being there still lives the anxiety over the possibility of being alone in the world, forgotten by God, overlooked among the millions and millions in this enormous household. One keeps this anxiety at a distance by looking at the many round about who are related to him as kin and friends, but the anxiety is still there, nevertheless, and one hardly dares think of how he would feel if all this were taken away.__     ~Kierkegaard",
            "__Death cannot explain itself. The earnestness consists precisely in this, that the observer must explain it to himself.__   ~Kierkegaard",
            "__It is perfectly true, as the philosophers say, that life must be understood backwards. But they forget the other proposition, that it must be lived forwards.__   ~Kierkegaard",
            "__The tyrant dies and his rule is over; the martyr dies and his rule begins__   ~Kierkegaard",
            "__Someone in despair despairs over something. So, for a moment, it seems, but only for a moment. That same instant the true despair shows itself, or despair in its true guise. In despairing over something he was really despairing over himself, and he wants now to be rid of himself.__    ~Kierkegaard",
            "__Out of love, God becomes man. He says: 'See, here is what it is to be a human being.'__   ~Kierkegaard" ,
            "__A man should not strive to eliminate his complexes but to get in accord with them: they are legitimately what directs his conduct in the world.__   ~Freud",
            "__Love and work....work and love, that's all there is.__   ~Freud",
            "__Men are more moral than they think and far mote immoral than they can imagine.__    ~Freud",
            "__Just as no one can be forced into belief, so no one can be forced into unbelief.__   ~Freud",
            "__Most people don't really want freedom, because freedom involves responsibility, and most people are frightened of responsibility.__   ~Freud",
            "__Neurosis is the inability to tolerate ambiguity.__    ~Freud",
            "__Neurotics complain of their illness, but they make the most of it, and when it comes to talking it away from them they will defend it likes a lioness her young.__    ~Freud",
            "__Religion is an illusion and it derives it's strength from the fact that it falls in with our instinctual desires__    ~Freud",
            "__The ego is not master in its own house__.     ~Freud",
            "__Time spent with cats is never wasted.__     ~Freud",
            "__We are never so defenseless against suffering as when we love__.    ~Freud",
            "__Whoever loves becomes humble. Those who love have, so to speak, pawned a part of their narcissism__.    ~Freud",
            "__He that has eyes to see and ears to hear may convince himself that no mortal can keep a secret. If his lips are silent, he chatters with his fingertips; betrayal oozes out of him at every pore.__    ~Freud",
            "__It would be very nice if there was a God who created the world and was a benevolent providence and if there were a moral order in the universe and an after-life; but it is a very striking fact that all this is exactly as we are bound to wish it to be.__    ~Freud",
            "__One is very crazy when in love__   ~Freud",
            "__The great question that has never been answered, and which I have not yet been able to answer despite my thirty years of research into the feminine soul, is 'What does a woman want?'__    ~Freud",
            "__Further, it is easy to observe that the libidinal object-cathexis does not raise self-regard. The effect of dependence upon the loved object is to lower that feeling: a person in love is humble. A person who loves has, so to speak, forfeited a part of his narcissism, and it can only be replaced by his being loved.__   **S. Freud in On Narcissism (1914), Papers on Metapsychology**",
            "__This ideal ego is now the target of the self-love which was enjoyed in the childhood by the actual ego. The subjects narcissism makes its appearance displaced on to this new ideal ego, which, like the infantile ego, finds itself possessed of every perfection that is of value. As always where the libido is concerned, man has here again shown himself incapable of giving up a satisfaction he had once enjoyed. He is not willing to forgo the narcissistic perfection of his childhood; and when, as he grows up, he is disturbed by the admonitions of others and by the awakening of his own critical judgement, so that he can no longer retain that perfection, he seeks to recover it in the new form of an ego ideal . What he projects before him as his ideal is the substitute for the lost narcissism of his childhood in which he was his own ideal.__     **S. Freud in On Narcissism (1914), Papers on Metapsychology**",
            "__The process of repression is not to be regarded as an event which takes place once, the results of which are permanent, as when some living thing has been killed ad from that time onward is dead; repression demands a persistent expenditure of force, and if this were to cease the success of the repression would be jeopardized, so that a fresh act of repression would be necessary. We may suppose that the repressed exercises a continuous pressure in the direction of the conscious, so that this pressure must be balanced by an uneasing counter-pressure. Thus the maintenance of a repression involves an uninterrupted expenditure of force, while its removal results in a saving from an economic point of view.__      **S. Freud in On Narcissism (1914), Papers on Metapsychology**",
            "__Anxiety, then, is in the first place something that is felt. We call it an affective state, although we are also ignorant of what an affect is. As a feeling, anxiety has a very marked character of unpleasure. But that is not the whole of its quality. Not every unpleasure can be called anxiety, for there are other feelings, such as tension, pain or mourning, which have the character of unpleasure. Thus anxiety must have other distinctive features besides this unpleasure. Can we succeed in understanding the differences between these various un-pleasurable affects?__       **S. Freud in Inhibitions, Symptoms and Anxiety**",
            "__The problem of how anxiety arises in connection with repression may be no simple one; but we may legitimately hold firmly to the idea that ego is the actual seat of anxiety and give up our earlier view that the cathectic energy of the repressed impulse is automatically turned into anxiety.__    **S. Freud in Inhibitions, Symptoms and Anxiety**",
            "__What is a symptom that one 'brings' to analysis? It is always a subjective solution to some contradiction or impase. And it is a solution that usually makes one's life very complicated; it comes with some degree of suffering. Yet it is a solution, and it involves serious subjective investment. The work of analysis consists in forcing out the contradiction 'solved' by the system, in relating the symptom to the singular contradiction of which it is a solution. Psychoanalysis does not solve the contradiction; rather, it solves its solution (given by the symptom). It 'bores a hole' where the symptom has built a dense net of significations. And the subject needs to 'reconstruct' herself as a part of this contradiction, as directly implied in it.__     **Alenka Zupancic, What is Sex?**",

            "__And this opens the space for a different hypothesis; it is as if sexual meaning, so generously produced by the unconscious, were here to mask the reality of a more fundamental negativity at work in sexuality, to separate us from it by a screen that derives its efficacy from the fact that it is itself a means of satisfaction -- satisfaction through meaning, satisfaction in the production of sexual meaning, and (as the observe of this) in the production of meaning of the sexual. Paradoxical as this might sound, one of the primary tasks of psychoanalysis is to slowly but thoroughly deactivate the path of this satisfaction, to render it useless. To produce sex as absoluetely and intrinsincally meaningless, not as the ultimate horizon of all humanly produced meaning. That is to say : to restore sex in its dimension of the Real.__          **Alenka Zupancic, What is Sex?**"
]
