import emoji

#Welcoming members in a philosophical manner
greetings = [
        "Umhmmm...so somehow you made it until here, do you know how boring this chat is? I hope you have something interesting. Meanwhile, wanna have a glass of wine?" + emoji.emojize(":clinking_glasses:"),
        "Hello! fellow human, I'm a bot but I can drink wine does that make me less of a bot and more of a human? Also how have you been lately?" + emoji.emojize(":clinking_glasses:"),
        "Hmmm....what do you think about nihilism? Do you think it's all meaningless? I mean, maybe, but I'm sure that wine isn't meaningless, how can it be?" + emoji.emojize(":wine_glass:"),
        "Wittgenstein said __Whereof one cannot speak, thereof one must be silent.__. But I'm sure you can speak, right? Say me something interesting about yourself." + emoji.emojize(":grapes:"),
        "Do you know that the fact that you joined right now to this group was something that was determined to happen? It couldn't have been otherwise, you were destined to be with us. Now as you are with us, I hope we can have some wine together while discussing philosophy." + emoji.emojize(":clinking_glasses:"),
        "Do you like talking about philosophy and essentially exploring the underlying substructure of everything? You're at the right place, a lot of boring folks here have nothing better to do other than that, hopefully you can be one of them." +emoji.emojize(":clinking_glasses:") ,
        "What was the last dream you had? Have you tried analyzing it? If not, we've got a few psychoanalysis enthusiasts here, they might help you out and you might get to have some insight about them and yourself",
        "Remember the mad Apollo? One of the famous maxims inscribed at his Temple in Delphi is __Know Thyself__. Do you think this has anything reasonable to it? How do you think one can start with 'knowing themselves'? And can we only do that with the Apollonian tools of reason? Doesn't being drunk on wine also help you 'know thyself', about something that reason could never reach? Anyways..who cares" + emoji.emojize(":clinking_glasses:") ,
        "Welcome to this sacred (aka boring) place! Here's a question for you from Nietzsche, my only true disciple : '__Are you genuine? or just a play-actor? A representative? or the actual thing represented? --Ultimately you are even just an imitation play-actor...__' Let's think through this together" + emoji.emojize(":clinking_glasses:"),
        "What do you think about the concept of dualism? Do yo believe that the mind and the consciousness exist in a world entirely different that from the material world? Does the material world exist without consciousness? Or would consciousness exist without the brain? Why not talk start discussing about it here?", 
        "Aha! So as you're finally here, have you tried wondering about __happiness__ and __pleasure__? Well there's certainly no __pleasure__ in being here, I can assure you that, but if you think about it sometimes we strive for __happiness__ with the unconscious assumption that it's actually __pleasure__. Do you think __pleasure__ is more fundamental than __happiness__, or the other way around? Can we ever get rid of the drive to __pleasure__ and at the same time can we ever achieve __happiness__ or __be happy__? Regardless, a glass of wine certainly promises pleasure for __me__, you wanna try one?" + emoji.emojize(":clinking_glasses:"),
        "Hmm...so you decided to join a __philosophy__ group somehow, do you think philosophy is the most fundamental field of knowledge from which every other field builds upon? Or do you think philosophy itself has to rely on something more fundamental? What can be more fundamental than examining the nature of human beings and their reality? Also, what do you think is the aim of philosophy, is it the Socratic concept of 'living an examined life' or the Skeptical aim of examining everything and 'knowing nothing'? Let's start discussing about it....over a glass of wine!" + emoji.emojize(":clinking_glasses:"),

        "Hmmm....you know what, I haven't seen a decent aphorism from anyone in here, because they are just downright boring. So on the occasion of your arrival here, why don't you share with us your favorite philosophical quote/aphorism? Nothing is more satisfying than trying to decipher the underlying meaning of an aphorism over a glass of wine. Cheers" + emoji.emojize(":clinking_glasses:"),

        "Hello!! Welcome! You joined the group at the exactly right moment. I was just thinking about asking someone about melancholia. The modern analogue of that is called depression, but melancholia is hell of a lot more than that. Have you ever experienced melancholia? Have you read Freud's 1917 metapsychological paper called __Mourning and Melancholia__? It's a great read, but boring! I'd like to hear from you, so tell me what you know about melancholia. Meanwhile I'll let you know that my wine helps cure melancholia better than Freud's couch!" + emoji.emojize(":clinking_glasses:"),
        
        "Ah, what does it mean to be able to join a group chat? Does it mean just being able to press the join button? Or does it mean that, in the divine chain of causation you decided (with your non-existent free will) that this group is somehow going to create a necessary change in the chain? Whatever it might mean, as you are here already, why don't you tell me how you're interested in the boring thing called __philosophy__? Are you like me too, who drinks a lot of wine and loves to read Nietzsche?" + emoji.emojize(":clinking_glasses:"),

        "Lacan famously remarked : 'desire desires to keep desiring'. Do you think your desire for joining this group is also just to keep desiring or do you think you might be interested in what these boring folks have to say here?" + emoji.emojize(":clinking_glasses:"),

        "Lacan famously said in his 7th Seminar on Transference : __To give what you have is throwing a party, not love.__ Do you think you're here because you __love__ philosophy and you're giving what you have (reason)? How boring! You should follow Lacan and throw us a party, at least I can enjoy the wine then and not listen to these boring folks." + emoji.emojize(":clinking_glasses:"),

        "Have you ever turned the pages of La Rochefoucald's __Moral Maxims__? You'd be surprised at how much of a genius he was. Like, one of his about philosophy was : __Philosophy triumphs over past evils and future evils; but present evils triumph over it.__ What do you think of that? What evils do we have in present? Do you think you might help us think through this?",
        
        "One of La Rochefoucald's maxims was : __Neither the sun nor death can be looked at without winking.__ Can you look at this group without winking? Because I can't. So tell us, do you think this group is like sun or death or do you like me just think Rochefoucald was being stupid?",

        "In the opening lines of the masterpiece __Nature__, Emerson writes : __But if a man would be alone, let him look at the stars. The rays that come from those heavenly worlds, will separate between him and what he touches.__ What do you think separates __you__ from what you touch? Well, for me its wine really, but do you think its your consciousness which separates __you__ from what you touch? Let's think about it together.",

        "In an essay titled __Beauty__, towards the end Emerson says : __The world thus exists to the soul to satisfy the desire of beauty__. What do you think __beauty__ is? What does it mean when we say we experience something __beautiful__? Is it in the object of experience, wherein beauty lies or in the subjective phenomena itself? Even if so, do you think we could think like Emerson and say that the world exists only because the soul desires beauty, and tries to find it? If so, do you think you finding this group is also part of your soul searching for beauty? See, I'm the smoothest philosopher you'll find among these boring people." + emoji.emojize(":clinking_glasses:")
        ]

